import type { Place, Festival } from './types'

export const places: Place[] = [
  {
    id: 'mathura',
    name: 'Mathura Nagri',
    nameEn: 'The Eternal City of Lord Krishna',
    icon: '🏙️',
    badge: 'Janm Bhoomi',
    distanceFromMathura: 'Braj ki Rajdhani',
    travelTime: 'Krishna Janm Bhoomi',
    heroTagline: 'Braj ki Rajdhani — Krishna Janm Bhoomi',
    intro: 'Yamuna Nadi ke pavitr tat par basi Mathura woh sthan hai jahan Dwapar Yug mein Bhagwan Shri Krishna ne Devaki aur Vasudev ke ghar janm liya tha. Yeh nagri 5,000 se adhik varsho ka itihaas samoeti hai — prachin mandir, ghato ki kashi, aur Kansa ki kahaniyan. Mathura aane wala har yatri ek alag hi anubhav lekar jaata hai.',
    bgGradient: 'linear-gradient(135deg, #EEF2FF, #C7D2FE)',
    cardDesc: 'Bhagwan Shri Krishna ka janm sthan. Yamuna ke kinarey, prachin ghat aur mandir se bhari yeh nagri Braj ka hridaya hai.',
    cardTags: ['Krishna Janmabhoomi', 'Vishram Ghat', 'Dwarkadhish'],
    temples: [
      {
        name: 'Shri Krishna Janmabhoomi',
        icon: '🛕',
        description: 'Bhagwan Krishna ka janm sthan — Mathura ka sabse pavitram sthal. Kara (prison cell) jahan Krishn ne janm liya, aaj bhi darshan yogya hai. Garbhagriha darshan lagatar — Bhagwat Bhawan 6:30 AM–1 PM | 4–9 PM.',
        summerTiming: 'Garbhagriha: 6:30 AM – 9:00 PM (lagatar)',
        entryFee: 'Entry Free',
      },
      {
        name: 'Dwarkadhish Mandir',
        icon: '🛕',
        description: '1814 mein nirmiit yeh mandir Vishram Ghat ke paas hai. Swarnambari shikhar aur sundar murti darshan. Raj Bhog aarti ka samay bahut khas hota hai.',
        summerTiming: '6:30 AM – 11:00 AM | 4:00 PM – 7:30 PM',
        entryFee: 'Entry Free',
      },
      {
        name: 'Vishram Ghat',
        icon: '🌊',
        description: 'Kansa vadh ke baad Krishna ne yahan vishram kiya tha. Sham ki Yamuna Aarti (6:30–7:00 PM) bahut hi manmohak hoti hai. Naav se ghat ka tour bhi lete hain.',
        summerTiming: 'All day (Yamuna Aarti 6:30–7 PM)',
        entryFee: 'Naav ₹30–100',
      },
      {
        name: 'Gita Mandir (Birla Temple)',
        icon: '🛕',
        description: 'Mathura-Vrindavan marg par sthit. Divaaron par Bhagavad Gita ke shlok khude hain. Laal pathhar se nirmiit, shant mahaul.',
        summerTiming: '5:00 AM – 12:00 PM | 3:00 PM – 9:00 PM',
        entryFee: 'Entry Free',
      },
      {
        name: 'Government Museum Mathura',
        icon: '🏛️',
        description: 'Kushan aur Gupta kaalin moortiyon ka behtareen collection. Archaeological rarities jo Mathura ki 2000 saal ki kalaa parampara dikhati hain.',
        summerTiming: '10:30 AM – 4:30 PM (Somwar band)',
        entryFee: '₹15 Indian | ₹150 Videshi',
      },
      {
        name: 'Kans Qila',
        icon: '🏰',
        description: 'Yamuna ke kinarey sthit prachin qila — maana jaata hai ki yeh Kansa ka qila tha. Purana hone ke bawajood aaj bhi itihaas ki gawah deta hai.',
        summerTiming: '9:00 AM – 6:00 PM',
        entryFee: 'Entry Free',
      },
    ],
    infoItems: [
      { label: 'Sab se Achha Time', value: 'Oct – March', note: 'Sardi ka mausam, Janmashtami bhi dhamakedar hoti hai (Aug/Sep)' },
      { label: 'Mathura Pahunchna', value: 'Train / Road', note: 'Mathura Junction — Delhi, Agra, Mumbai se seedhi train' },
      { label: 'Local Transport', value: 'E-Rickshaw / Auto', note: '₹10–50 mein shehar mein ghoomne ke liye kafi hai' },
      { label: 'Prasad', value: 'Mathura Ka Peda', note: 'Sunder lal Joshi ki dukaan se original Mathura Peda zaroor lein' },
    ],
  },
  {
    id: 'vrindavan',
    name: 'Vrindavan Dham',
    nameEn: 'The Sacred Forest of Krishna\'s Childhood',
    icon: '🌿',
    badge: 'Leela Bhoomi',
    distanceFromMathura: '12 km',
    travelTime: '20–30 min drive',
    heroTagline: 'Krishna ki Leela Bhoomi — Mathura se 12 km',
    intro: 'Vrindavan woh pavitrtam sthan hai jahan Bhagwan Shri Krishna ne Gopis ke saath Raas Leela ki, Kalia Nag ko nacha aur apni bansi se poore Braj ko sanjiva kiya. Aaj bhi yahan 5,000 se adhik mandir hain. Keshi Ghat ka sunset, Banke Bihari ka darshan aur Prem Mandir ki roshni — har cheez yahan divya lagti hai.',
    bgGradient: 'linear-gradient(135deg, #F0FDF4, #BBF7D0)',
    cardDesc: 'Yahan Shri Krishna ne apna bachpan aur kishori avastha bitti. 5,000 se adhik mandiron ka yeh pavitr nagr bhakton ka swarg hai.',
    cardTags: ['Banke Bihari', 'Prem Mandir', 'ISKCON'],
    temples: [
      {
        name: 'Banke Bihari Mandir',
        icon: '🛕',
        description: '1864 mein Swami Haridas ke bhakti ke fal swarup prakatt hue Banke Bihari ji. Curtain darshan ki parampara — har kuch minute baad parda girta hai. Festival mein crowd bahut hota hai, week days prefer karein.',
        summerTiming: '7:00 AM – 12:30 PM | 4:15 PM – 9:30 PM',
        winterTiming: '8:45 AM – 1:00 PM | 4:30 PM – 8:30 PM',
        entryFee: 'Entry Free',
      },
      {
        name: 'Prem Mandir',
        icon: '🕌',
        description: '2012 mein nirmiit Italian white marble ka yeh mandir 54 acres mein faila hai. Govardhan Leela, Raas Leela ki sculptures. Sham 7:15 PM par light & fountain show — bilkul free. 30–40 min ka show hai.',
        summerTiming: '5:30 AM – 12:00 PM | 4:30 PM – 8:30 PM (Light Show ~7:15 PM)',
        entryFee: 'Entry Free | Parking: ₹30 (2W) ₹100 (Car)',
      },
      {
        name: 'ISKCON Temple (Krishna Balaram)',
        icon: '🏛️',
        description: 'Srila Prabhupada dwara sthaapit. White marble, sundar garden, daily aarti schedule. Aarti timing zaroor dekhe. Guest house bhi available. World-class mandir.',
        summerTiming: '4:30 AM – 8:30 PM (Aarti 6 baar)',
        entryFee: 'Entry Free',
      },
      {
        name: 'Radha Raman Mandir',
        icon: '🛕',
        description: '1542 mein Gopala Bhatta Goswami ko svayambhu prakaṭ hue Radha Raman ji. 16 baar ke shringar ke saath roz aarti. Aarti timing bahut khas aur nigam-anusar.',
        summerTiming: '7:00 AM – 12:00 PM | 5:00 PM – 9:00 PM',
        entryFee: 'Entry Free',
      },
      {
        name: 'Nidhivan',
        icon: '🌿',
        description: 'Prachin tulsi ka vana jahan Krishna raat ko Raas Leela karte hain — aisi manyata hai. Sham 8 baje ke baad koi andar nahi rehta. Swami Haridas ki samadhi bhi yahan hai.',
        summerTiming: '9:00 AM – 8:00 PM (raat ko band)',
        entryFee: 'Entry Free',
      },
      {
        name: 'Keshi Ghat',
        icon: '🌊',
        description: 'Yamuna ke kinare sabse sundar ghat jahan Krishna ne Keshi asur ka vadh kiya tha. Sunset yahan dekhna ek unique anubhav hai. Boat ride available.',
        summerTiming: 'All day (Sham ki Aarti 6 PM)',
        entryFee: 'Free | Naav ₹50–200',
      },
    ],
    infoItems: [
      { label: 'Sabse Pehle Yahan Jayen', value: 'Banke Bihari (Subah)', note: '7:00–9 AM ke beech kam bheed hoti hai' },
      { label: 'Sham ko Must-Do', value: 'Prem Mandir Light Show', note: '6:30 PM pahunch jayen — acchi jagah milegi' },
      { label: 'Rukne Ki Jagah', value: 'Prem Mandir Ke Paas', note: 'AC hotels ₹1,299/- se | Dharamshala ₹399/-' },
      { label: 'Dress Code', value: 'Salwar/Dhoti-Kurta', note: 'Shalini kapde zaroor pahnein — sanctum mein jootey nahi' },
    ],
  },
  {
    id: 'barsana',
    name: 'Barsana',
    nameEn: 'Birthplace of Shrimati Radha Rani',
    icon: '🌸',
    badge: 'Radha Niwas',
    distanceFromMathura: '43 km',
    travelTime: '~1 ghante ki drive',
    heroTagline: 'Radha Rani Ka Janm Sthan — Mathura se 43 km',
    intro: 'Mathura se 43 km door pahadi par basa Barsana ek chhoti si nagri hai, lekin iske aatmik mahatva ka koi thikana nahi. Yahan Radha Rani ka janm hua tha — Maharaj Vrishabhanu aur Mata Kirtti ke ghar. Bhanugarh pahad par sthit Shri Ladli Ji Mandir (Radha Rani Temple) tak 200 seedhiyan chadh kar darshan milta hai. Aur Holi? Barsana ki Lathmar Holi duniya bhar mein mashhoor hai.',
    bgGradient: 'linear-gradient(135deg, #FFF0F3, #FECDD3)',
    cardDesc: 'Shrimati Radha Rani ka janm sthan. Bhanugarh pahad par sthit Radha Rani Mandir aur Lathmar Holi ke liye world-famous.',
    cardTags: ['Radha Rani Mandir', 'Lathmar Holi'],
    temples: [
      {
        name: 'Shri Radha Rani Mandir (Ladli Ji)',
        icon: '👸',
        description: 'Bhanugarh pahad par 200 seedhiyon ke baad yeh mandir hai. Radha Rani ki murti yahaan adbhut hai. Upar se poore Barsana aur Nandgaon ka view milta hai.',
        summerTiming: '5:00 AM – 12:00 PM | 4:30 PM – 9:00 PM',
        entryFee: 'Entry Free',
      },
      {
        name: 'Maan Mandir',
        icon: '🏛️',
        description: 'Barsana ke mukhya mandiron mein se ek — yahan Radha aur Krishna ki ek khaas leela — "Maan Leela" ke liye jana jaata hai. Rang Birangi nakkashi.',
        summerTiming: '6:00 AM – 12:00 PM | 5:00 PM – 8:30 PM',
        entryFee: 'Entry Free',
      },
      {
        name: 'Lathmar Holi (Utsav)',
        icon: '🎨',
        description: 'Phagun ekadashi se pehle — Barsana ki mahilaen Nandgaon ke purushon ko lathon se marti hain aur gujhiya-abeer ka utsav hota hai. Poori duniya se log dekhne aate hain.',
        summerTiming: 'Phagun Ekadashi (Feb/March)',
        entryFee: 'Koi ticket nahi — Pahle aayen!',
      },
    ],
    infoItems: [
      { label: 'Barsana Pahunchna', value: 'Mathura se Bus/Taxi', note: 'Mathura bus stand se Barsana bus milti hai — ₹60-80' },
      { label: 'Seedhiyan', value: '~200 Seedhiyan', note: 'Chadhne mein 15-20 min — danda saath lein, budhapa mein thoda tough' },
      { label: 'Holi Ka Din', value: 'Feb ya March', note: 'Hindu calendar ke hisab se — Phagun Ekadashi' },
    ],
  },
  {
    id: 'nandgaon',
    name: 'Nandgaon',
    nameEn: 'The Village of Nanda Maharaja',
    icon: '🥛',
    badge: 'Nand Baba Nagri',
    distanceFromMathura: '50 km',
    travelTime: 'Barsana se 8 km',
    heroTagline: 'Nand Baba Ka Gaon — Mathura se 50 km',
    intro: 'Nandgaon woh gaon hai jahan Nand Baba aur Yashoda Maiya ne Krishna aur Balaram ka palan-poshan kiya. Barsana se sirf 8 km door, yeh gaon ek pahad ke oopar basa hua hai. Nand Bhawan — woh sthan jahan Nanda Maharaj rehte the — aur Nand Rai Mandir yahaan ke pramukh darshan sthaan hain. Holi ka Rang yahan bhi bahut khas hota hai — Barsana ki Lathmar Holi ke ek din baad Nandgaon ki Holi manai jaati hai.',
    bgGradient: 'linear-gradient(135deg, #FEFCE8, #FEF08A)',
    cardDesc: 'Nand Baba aur Yashoda Maiya ka gaon — jahan Kanha ka palan-poshan hua. Nand Bhawan aur Nand Rai Mandir yahan ke mukhya darshan sthaan hain.',
    cardTags: ['Nand Bhawan', 'Nandotsav'],
    temples: [
      {
        name: 'Nand Bhawan',
        icon: '🏠',
        description: 'Woh ghar jahan Nanda Maharaj rehte the aur jahan Bal Krishna ne apni balyavastha bitai. Pahad par sthit — upar se poora gaon aur khet dikhte hain.',
        summerTiming: '6:00 AM – 12:00 PM | 4:00 PM – 8:00 PM',
        entryFee: 'Entry Free',
      },
      {
        name: 'Nand Rai Mandir',
        icon: '🛕',
        description: 'Nand Baba aur Yashoda Maiya ki murti ke saath Bal Krishna ka sunder swaroop. Mandir ki nakkashi bahut hi khoobsoorat hai.',
        summerTiming: '6:00 AM – 12:00 PM | 4:00 PM – 8:30 PM',
        entryFee: 'Entry Free',
      },
    ],
    infoItems: [
      { label: 'Nandgaon Pahunchna', value: 'Barsana se 8 km', note: 'Auto/taxi se — Barsana darshan ke baad same din possible' },
      { label: 'Holi Ka Tyohar', value: 'Phagun Dwadashi', note: 'Barsana Holi ke ek din baad — utna hi dhamakedar' },
    ],
  },
  {
    id: 'goverdhan',
    name: 'Goverdhan',
    nameEn: 'The Holy Hill Lifted by Krishna',
    icon: '⛰️',
    badge: 'Parikrama Sthal',
    distanceFromMathura: '25 km',
    travelTime: '40–50 min drive',
    heroTagline: 'Giridhari Ka Parvat — Mathura se 25 km',
    intro: 'Yeh woh parvat hai jise Bhagwan Shri Krishna ne apni chhoti si anguli par utha liya tha — Indra ke krodh se Braj ke vaasiyon aur pasuon ki raksha ke liye. 7 din tak kaha raha yeh Shailraj — tab se krishna ka naam "Giridhari" bhi pada. 21 km ki parikrama karna ek adhyatmik tapasya hai jise lakho log nange paon karte hain. Radha Kund aur Shyam Kund yahan ke sabse pavitram sarovar hain.',
    bgGradient: 'linear-gradient(135deg, #F0FDF4, #86EFAC)',
    cardDesc: 'Bhagwan ne jis parvat ko anguli par uthaya tha — Goverdhan Parikrama (21 km) ek mahaan tapasya hai. Radha Kund aur Kusum Sarovar bhi yahan hain.',
    cardTags: ['Goverdhan Parikrama', 'Radha Kund', 'Kusum Sarovar'],
    temples: [
      {
        name: 'Goverdhan Parikrama (21 km)',
        icon: '🏔️',
        description: 'Goverdhan parvat ki 21 km ki parikrama — puri duniya mein ek anokha aatmik anubhav. Nange paon, Hare Krishna kirtan karte hue, lakh-do lakh log ek saath chalte hain. Kartik maas mein sabse zyada bheed.',
        summerTiming: 'Anytime (Subah se Sham)',
        entryFee: 'Bilkul Free',
      },
      {
        name: 'Radha Kund & Shyam Kund',
        icon: '🏊',
        description: 'Bahut hi pavitram do sarovar — Radha aur Krishna dwara nirmit maane jaate hain. Snan karna moksha data hai — aisi manyata hai. Sharad Purnima ko yahan snan ka vishesh mahatva hai.',
        summerTiming: '5:00 AM – 7:00 PM',
        entryFee: 'Free',
      },
      {
        name: 'Kusum Sarovar',
        icon: '🌊',
        description: 'Goverdhan ke raste mein ek sundar sarovar — maana jaata hai yahan Radha rani phool chuni karti thin. Mughal-kaalin chhatriyan aur ghaat bahut khubsoorat hai.',
        summerTiming: '6:00 AM – 6:00 PM',
        entryFee: 'Free',
      },
      {
        name: 'Manasi Ganga',
        icon: '🛕',
        description: 'Goverdhan parvat ke beech mein sthit ek chhota sa sarovar. Yahan snan aur deepdan ka vishesh mahatva hai. Deepdan Purnima ke din yahan hazar deepak jalte hain.',
        summerTiming: '5:00 AM – 8:00 PM',
        entryFee: 'Free',
      },
    ],
    infoItems: [
      { label: 'Parikrama Dur', value: '21 Km', note: '~5-7 ghante nange paon, ya 3-4 ghante cycle se' },
      { label: 'Sabse Achhi Date', value: 'Kartik Maas', note: 'Lakho logon ke saath — Goverdhan Puja (Diwali+1)' },
      { label: 'Goverdhan Pahuchna', value: 'Mathura se Bus/Car', note: 'Bus: ₹40-60 | Taxi: ₹400-600 round trip' },
    ],
  },
  {
    id: 'gokul',
    name: 'Gokul',
    nameEn: "The Land of Krishna's Infant Miracles",
    icon: '🪷',
    badge: 'Bal Leela Bhoomi',
    distanceFromMathura: '15 km',
    travelTime: '25–35 min drive',
    heroTagline: 'Bal Krishna Ki Leela Bhoomi — Mathura se 15 km',
    intro: 'Gokul woh sthan hai jahan Vasudeva ne Kans ke bhay se Krishna ko raat ke andheron mein Yamuna par lekar nand baba ke ghar chhoda tha. Yahan Bal Krishna ne apni shuruwati leelayein ki — Pootna badh, Shakatasura badh, aur anek adbhut kaarya. Gokul aaj bhi ek shant, chota sa gaon hai jahan Yamuna ke teer par ghaat aur prachin mandir hain.',
    bgGradient: 'linear-gradient(135deg, #FFF7ED, #FED7AA)',
    cardDesc: 'Yahan Nand Baba ne Kanha ko Kansa se bachane ke liye laaye the. Gokul ke ghat aur Brahmand Ghat ka darshan atya anand deta hai.',
    cardTags: ['Gokulnath Mandir', 'Brahmand Ghat'],
    temples: [
      {
        name: 'Gokul Nath Mandir',
        icon: '🛕',
        description: 'Gokul ka pramukh mandir jahan Shri Gokulanath (Krishna) ki murti hai. Pushtimarg ke anusar yahan roz seva hoti hai. Haveli-shaili mein nirmiit.',
        summerTiming: '6:00 AM – 11:00 AM | 5:00 PM – 8:00 PM',
        entryFee: 'Entry Free',
      },
      {
        name: 'Brahmand Ghat',
        icon: '🌊',
        description: 'Yahan Yashoda Maiya ne Krishna ke muh mein poora brahmand dekha tha — "Brahmand Darshan" ki jagah. Yamuna ke kinare sundar ghaat aur shant mahaul.',
        summerTiming: 'All day (Ghat 24 ghante khula)',
        entryFee: 'Free',
      },
      {
        name: 'Raman Reti',
        icon: '🏛️',
        description: 'Yahan ki pavitir reti — maana jaata hai Krishna aur Balram yahan khelte the. Iss reti ka tilak karna shubh maana jaata hai. Swami Ji ka ashram bhi yahan hai.',
        summerTiming: '6:00 AM – 7:00 PM',
        entryFee: 'Free',
      },
    ],
    infoItems: [
      { label: 'Distance', value: 'Mathura se 15 km', note: 'Auto ya taxi se — Mathura + Gokul ek din mein possible' },
      { label: 'Khaas Tyohar', value: 'Nandotsav', note: 'Janmashtami+1 — Krishna janm ki khushi mein dhoom' },
    ],
  },
]

export const festivals: Festival[] = [
  {
    name: 'Lathmar Holi — Barsana',
    icon: '🎨',
    description: 'Duniya ki sabse mashoor Holi — Nandgaon ke gwaale Barsana ki mahilaon se rang khelne aate hain, aur mahilaen unhe latthon se marti hain. Ek ekdum anokha nazaara.',
    month: 'Phagun Ekadashi (Feb/March) — Barsana mein',
    location: 'Barsana',
  },
  {
    name: 'Nandgaon Holi',
    icon: '🎉',
    description: 'Barsana ki Holi ke ek din baad — Phagun Dwadashi. Yahan bhi rang aur lathon ka khel hota hai — utna hi colorful aur bhaavpurna.',
    month: 'Phagun Dwadashi — Nandgaon mein',
    location: 'Nandgaon',
  },
  {
    name: 'Holi — Vrindavan/Mathura',
    icon: '🌸',
    description: 'Vrindavan mein Holi ek hafte tak chalta hai — Phoolwali Holi (phoolon ki Holi), Widow Holi, aur regular Holi. Puri duniya se tourists aate hain.',
    month: 'Phagun Purnima (March)',
    location: 'Vrindavan/Mathura',
  },
  {
    name: 'Janmashtami',
    icon: '🪔',
    description: 'Krishna ke janm ka din — Mathura, Vrindavan, Dwarkadhish, Banke Bihari sab jagah midnight ko jhankiyan aur celebrations. Lakho devotee aate hain — pahle se hotel book karein.',
    month: 'Bhadrapad Krishna Ashtami (August/September)',
    location: 'Mathura/Vrindavan',
  },
  {
    name: 'Radhashtami',
    icon: '🌼',
    description: 'Radha Rani ka janm din — Barsana aur Vrindavan mein vishesh aarti aur jhankiyan. Banke Bihari mein Raas Leela staged hoti hai.',
    month: 'Bhadrapad Shukla Ashtami (August/September)',
    location: 'Barsana/Vrindavan',
  },
  {
    name: 'Goverdhan Puja',
    icon: '⛰️',
    description: 'Diwali ke ek din baad — Goverdhan parvat ki pooja aur Annakut (56 bhog). Lakho log parikrama karte hain. Kartik maas ka sab se bada tyohar.',
    month: 'Kartik Shukla Pratipada (October/November)',
    location: 'Goverdhan',
  },
  {
    name: 'Kartik Maas',
    icon: '🌕',
    description: 'Poora kartik maas Vrindavan mein khichawali, Goverdhan parikrama aur deepdan ka maas hai. Har din kuch na kuch khaas hota hai. Sabs se zyada bheer bhi isi maas mein hoti hai.',
    month: 'October – November (puri maas)',
    location: 'Vrindavan',
  },
  {
    name: 'Sharad Purnima',
    icon: '🪅',
    description: 'Iss raat Krishna ne Gopis ke saath Maha Raas Leela ki thi. Vrindavan ke mandiron mein raat bhar jhankiyan aur kirtan. Radha Kund snan ka vishesh mahatva.',
    month: 'Ashwin Purnima (September/October)',
    location: 'Vrindavan',
  },
]
